.uno/ux11/MainView.g.uno
.uno/ux11/pan.Button.g.uno
.uno/ux11/pan.Page.g.uno
.uno/ux11/pan.Text.g.uno
.uno/ux11/pan.TextInput.g.uno
.uno/ux11/AddBloodGlucose.g.uno
.uno/ux11/HomePage.g.uno
.uno/ux11/Readings.g.uno
.uno/ux11/Separator.g.uno
.uno/ux11/pancreamatic.unoproj.g.uno